#!/bin/bash
#
# Copyright (c) 2011-2013  University of Texas at Austin. All rights reserved.
#
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# This file is part of PerfExpert.
#
# PerfExpert is free software: you can redistribute it and/or modify it under
# the terms of the The University of Texas at Austin Research License
# 
# PerfExpert is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.
# 
# Authors: Leonardo Fialho and Ashay Rane
#
# $HEADER$
#

# Create a test directory
echo Creating test directory...
mkdir -p multiple_dirs.test/compute
cd multiple_dirs.test

# Copy the original source code
echo Copying test program file...
cp ${PERFEXPERT_SRCDIR}/tests/multiple_dirs/compute/compute.c ./compute/
cp ${PERFEXPERT_SRCDIR}/tests/multiple_dirs/omp_mm.c .
cp ${PERFEXPERT_SRCDIR}/tests/multiple_dirs/omp_mm.h .
cp ${PERFEXPERT_SRCDIR}/tests/multiple_dirs/Makefile .

# Create a local database
echo Creating test database...
sqlite3 ./test.db < ${PERFEXPERT_SRCDIR}/contrib/recommender.db.txt

# Call PerfExpert
echo Running test...
OMP_NUM_THREADS=16 perfexpert -l 10 -c -d ./test.db -r 10 -m all 0.1 ./test
RC=$?

# Did we got the expected result?
echo Test return code: $RC
if [ "1" -eq "$RC" ]; then
	exit -1
fi
if [ "127" -eq "$RC" ]; then
	echo Unable to run PerfExpert
	exit -1
fi
exit 0

# EOF
